import type { MenuItem } from 'core/base/type/menu';

export const MENU_MOCK_ITEMS: MenuItem[] = [
    {
        id: 'menu-1',
        name: 'Chicken Dum Biryani',
        category: 'Rice & Biryani',
        foodType: 'Non-Veg',
        description: 'Fragrant basmati layered with spiced chicken, sealed and slow-cooked.',
        servingSize: '250g',
        ingredients: ['Basmati rice', 'Chicken', 'Saffron', 'Fried onions'],
        variants: [
            { id: 'v-1-1', label: '500g', price: '249', offerPrice: '199' },
            { id: 'v-1-2', label: '1kg', price: '449' },
        ],
        status: 'Active',
        nutritionApproved: true,
    },
    {
        id: 'menu-2',
        name: 'Paneer Butter Masala',
        category: 'Curries',
        foodType: 'Veg',
        description: 'Cottage cheese simmered in a rich tomato-cashew gravy.',
        servingSize: '200g',
        ingredients: ['Paneer', 'Tomato', 'Cashew', 'Cream'],
        variants: [{ id: 'v-2-1', label: 'Regular', price: '199' }],
        status: 'Active',
        nutritionApproved: false,
    },
    {
        id: 'menu-3',
        name: 'Crispy Veg Starters Platter',
        category: 'Starters',
        foodType: 'Veg',
        description: 'Assorted crispy vegetarian starters with mint chutney.',
        servingSize: '300g',
        ingredients: ['Potato', 'Corn', 'Breadcrumbs', 'Mint'],
        variants: [{ id: 'v-3-1', label: 'Platter', price: '179', offerPrice: '149' }],
        status: 'Inactive',
        nutritionApproved: false,
    },
    {
        id: 'menu-4',
        name: 'Butter Naan (2 pc)',
        category: 'Breads',
        foodType: 'Veg',
        description: 'Soft tandoor-baked naan brushed with butter.',
        servingSize: '2 pc',
        ingredients: ['Flour', 'Butter', 'Yeast'],
        variants: [{ id: 'v-4-1', label: '2 pc', price: '59' }],
        status: 'Active',
        nutritionApproved: true,
    },
    {
        id: 'menu-5',
        name: 'Gulab Jamun (4 pc)',
        category: 'Desserts',
        foodType: 'Veg',
        description: 'Warm milk dumplings soaked in rose-cardamom syrup.',
        servingSize: '4 pc',
        ingredients: ['Milk solids', 'Sugar', 'Rose water', 'Cardamom'],
        variants: [{ id: 'v-5-1', label: '4 pc', price: '99' }],
        status: 'Active',
        nutritionApproved: false,
    },
    {
        id: 'menu-6',
        name: 'Mango Lassi',
        category: 'Beverages',
        foodType: 'Veg',
        description: 'Thick yogurt blended with alphonso mango pulp.',
        servingSize: '300ml',
        ingredients: ['Mango', 'Yogurt', 'Sugar'],
        variants: [{ id: 'v-6-1', label: '300ml', price: '89' }],
        status: 'Inactive',
        nutritionApproved: true,
    },
];
